class PhoneCode {
  final String name;
  final String code;
  const PhoneCode({required this.name, required this.code});
}

const List<String> countriesList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];

const List<PhoneCode> phoneCodes = [
  PhoneCode(name: "Afghanistan", code: "+93"),
  PhoneCode(name: "Albania", code: "+355"),
  PhoneCode(name: "Algeria", code: "+213"),
  PhoneCode(name: "American Samoa", code: "+1-684"),
  PhoneCode(name: "Andorra", code: "+376"),
  PhoneCode(name: "Angola", code: "+244"),
  PhoneCode(name: "Anguilla", code: "+1-264"),
  PhoneCode(name: "Antigua and Barbuda", code: "+1-268"),
  PhoneCode(name: "Argentina", code: "+54"),
  PhoneCode(name: "Armenia", code: "+374"),
  PhoneCode(name: "Aruba", code: "+297"),
  PhoneCode(name: "Australia", code: "+61"),
  PhoneCode(name: "Austria", code: "+43"),
  PhoneCode(name: "Azerbaijan", code: "+994"),
  PhoneCode(name: "Bahamas", code: "+1-242"),
  PhoneCode(name: "Bahrain", code: "+973"),
  PhoneCode(name: "Bangladesh", code: "+880"),
  PhoneCode(name: "Barbados", code: "+1-246"),
  PhoneCode(name: "Belarus", code: "+375"),
  PhoneCode(name: "Belgium", code: "+32"),
  PhoneCode(name: "Belize", code: "+501"),
  PhoneCode(name: "Benin", code: "+229"),
  PhoneCode(name: "Bermuda", code: "+1-441"),
  PhoneCode(name: "Bhutan", code: "+975"),
  PhoneCode(name: "Bolivia", code: "+591"),
  PhoneCode(name: "Bosnia and Herzegovina", code: "+387"),
  PhoneCode(name: "Botswana", code: "+267"),
  PhoneCode(name: "Brazil", code: "+55"),
  PhoneCode(name: "British Virgin Islands", code: "+1-284"),
  PhoneCode(name: "Brunei", code: "+673"),
  PhoneCode(name: "Bulgaria", code: "+359"),
  PhoneCode(name: "Burkina Faso", code: "+226"),
  PhoneCode(name: "Burundi", code: "+257"),
  PhoneCode(name: "Cabo Verde", code: "+238"),
  PhoneCode(name: "Cambodia", code: "+855"),
  PhoneCode(name: "Cameroon", code: "+237"),
  PhoneCode(name: "Canada", code: "+1"),
  PhoneCode(name: "Cayman Islands", code: "+1-345"),
  PhoneCode(name: "Central African Republic", code: "+236"),
  PhoneCode(name: "Chad", code: "+235"),
  PhoneCode(name: "Chile", code: "+56"),
  PhoneCode(name: "China", code: "+86"),
  PhoneCode(name: "Colombia", code: "+57"),
  PhoneCode(name: "Comoros", code: "+269"),
  PhoneCode(name: "Congo (Congo-Brazzaville)", code: "+242"),
  PhoneCode(name: "Costa Rica", code: "+506"),
  PhoneCode(name: "Croatia", code: "+385"),
  PhoneCode(name: "Cuba", code: "+53"),
  PhoneCode(name: "Cyprus", code: "+357"),
  PhoneCode(name: "Czechia", code: "+420"),
  PhoneCode(name: "Democratic Republic of the Congo", code: "+243"),
  PhoneCode(name: "Denmark", code: "+45"),
  PhoneCode(name: "Djibouti", code: "+253"),
  PhoneCode(name: "Dominica", code: "+1-767"),
  PhoneCode(name: "Dominican Republic", code: "+1-809"),
  PhoneCode(name: "Ecuador", code: "+593"),
  PhoneCode(name: "Egypt", code: "+20"),
  PhoneCode(name: "El Salvador", code: "+503"),
  PhoneCode(name: "Equatorial Guinea", code: "+240"),
  PhoneCode(name: "Eritrea", code: "+291"),
  PhoneCode(name: "Estonia", code: "+372"),
  PhoneCode(name: "Eswatini", code: "+268"),
  PhoneCode(name: "Ethiopia", code: "+251"),
  PhoneCode(name: "Fiji", code: "+679"),
  PhoneCode(name: "Finland", code: "+358"),
  PhoneCode(name: "France", code: "+33"),
  PhoneCode(name: "French Guiana", code: "+594"),
  PhoneCode(name: "Gabon", code: "+241"),
  PhoneCode(name: "Gambia", code: "+220"),
  PhoneCode(name: "Georgia", code: "+995"),
  PhoneCode(name: "Germany", code: "+49"),
  PhoneCode(name: "Ghana", code: "+233"),
  PhoneCode(name: "Gibraltar", code: "+350"),
  PhoneCode(name: "Greece", code: "+30"),
  PhoneCode(name: "Greenland", code: "+299"),
  PhoneCode(name: "Grenada", code: "+1-473"),
  PhoneCode(name: "Guadeloupe", code: "+590"),
  PhoneCode(name: "Guam", code: "+1-671"),
  PhoneCode(name: "Guatemala", code: "+502"),
  PhoneCode(name: "Guinea", code: "+224"),
  PhoneCode(name: "Guinea-Bissau", code: "+245"),
  PhoneCode(name: "Guyana", code: "+592"),
  PhoneCode(name: "Haiti", code: "+509"),
  PhoneCode(name: "Honduras", code: "+504"),
  PhoneCode(name: "Hong Kong", code: "+852"),
  PhoneCode(name: "Hungary", code: "+36"),
  PhoneCode(name: "Iceland", code: "+354"),
  PhoneCode(name: "India", code: "+91"),
  PhoneCode(name: "Indonesia", code: "+62"),
  PhoneCode(name: "Iran", code: "+98"),
  PhoneCode(name: "Iraq", code: "+964"),
  PhoneCode(name: "Ireland", code: "+353"),
  PhoneCode(name: "Israel", code: "+972"),
  PhoneCode(name: "Italy", code: "+39"),
  PhoneCode(name: "Ivory Coast", code: "+225"),
  PhoneCode(name: "Jamaica", code: "+1-876"),
  PhoneCode(name: "Japan", code: "+81"),
  PhoneCode(name: "Jordan", code: "+962"),
  PhoneCode(name: "Kazakhstan", code: "+7"),
  PhoneCode(name: "Kenya", code: "+254"),
  PhoneCode(name: "Kiribati", code: "+686"),
  PhoneCode(name: "Kuwait", code: "+965"),
  PhoneCode(name: "Kyrgyzstan", code: "+996"),
  PhoneCode(name: "Laos", code: "+856"),
  PhoneCode(name: "Latvia", code: "+371"),
  PhoneCode(name: "Lebanon", code: "+961"),
  PhoneCode(name: "Lesotho", code: "+266"),
  PhoneCode(name: "Liberia", code: "+231"),
  PhoneCode(name: "Libya", code: "+218"),
  PhoneCode(name: "Liechtenstein", code: "+423"),
  PhoneCode(name: "Lithuania", code: "+370"),
  PhoneCode(name: "Luxembourg", code: "+352"),
  PhoneCode(name: "Macau", code: "+853"),
  PhoneCode(name: "Madagascar", code: "+261"),
  PhoneCode(name: "Malawi", code: "+265"),
  PhoneCode(name: "Malaysia", code: "+60"),
  PhoneCode(name: "Maldives", code: "+960"),
  PhoneCode(name: "Mali", code: "+223"),
  PhoneCode(name: "Malta", code: "+356"),
  PhoneCode(name: "Marshall Islands", code: "+692"),
  PhoneCode(name: "Martinique", code: "+596"),
  PhoneCode(name: "Mauritania", code: "+222"),
  PhoneCode(name: "Mauritius", code: "+230"),
  PhoneCode(name: "Mexico", code: "+52"),
  PhoneCode(name: "Micronesia", code: "+691"),
  PhoneCode(name: "Moldova", code: "+373"),
  PhoneCode(name: "Monaco", code: "+377"),
  PhoneCode(name: "Mongolia", code: "+976"),
  PhoneCode(name: "Montenegro", code: "+382"),
  PhoneCode(name: "Montserrat", code: "+1-664"),
  PhoneCode(name: "Morocco", code: "+212"),
  PhoneCode(name: "Mozambique", code: "+258"),
  PhoneCode(name: "Myanmar", code: "+95"),
  PhoneCode(name: "Namibia", code: "+264"),
  PhoneCode(name: "Nauru", code: "+674"),
  PhoneCode(name: "Nepal", code: "+977"),
  PhoneCode(name: "Netherlands", code: "+31"),
  PhoneCode(name: "New Zealand", code: "+64"),
  PhoneCode(name: "Nicaragua", code: "+505"),
  PhoneCode(name: "Niger", code: "+227"),
  PhoneCode(name: "Nigeria", code: "+234"),
  PhoneCode(name: "North Korea", code: "+850"),
  PhoneCode(name: "North Macedonia", code: "+389"),
  PhoneCode(name: "Norway", code: "+47"),
  PhoneCode(name: "Oman", code: "+968"),
  PhoneCode(name: "Pakistan", code: "+92"),
  PhoneCode(name: "Palau", code: "+680"),
  PhoneCode(name: "Palestine State", code: "+970"),
  PhoneCode(name: "Panama", code: "+507"),
  PhoneCode(name: "Papua New Guinea", code: "+675"),
  PhoneCode(name: "Paraguay", code: "+595"),
  PhoneCode(name: "Peru", code: "+51"),
  PhoneCode(name: "Philippines", code: "+63"),
  PhoneCode(name: "Poland", code: "+48"),
  PhoneCode(name: "Portugal", code: "+351"),
  PhoneCode(name: "Puerto Rico", code: "+1-787"),
  PhoneCode(name: "Qatar", code: "+974"),
  PhoneCode(name: "Romania", code: "+40"),
  PhoneCode(name: "Russia", code: "+7"),
  PhoneCode(name: "Rwanda", code: "+250"),
  PhoneCode(name: "Saint Kitts and Nevis", code: "+1-869"),
  PhoneCode(name: "Saint Lucia", code: "+1-758"),
  PhoneCode(name: "Saint Vincent and the Grenadines", code: "+1-784"),
  PhoneCode(name: "Samoa", code: "+685"),
  PhoneCode(name: "San Marino", code: "+378"),
  PhoneCode(name: "Sao Tome and Principe", code: "+239"),
  PhoneCode(name: "Saudi Arabia", code: "+966"),
  PhoneCode(name: "Senegal", code: "+221"),
  PhoneCode(name: "Serbia", code: "+381"),
  PhoneCode(name: "Seychelles", code: "+248"),
  PhoneCode(name: "Sierra Leone", code: "+232"),
  PhoneCode(name: "Singapore", code: "+65"),
  PhoneCode(name: "Slovakia", code: "+421"),
  PhoneCode(name: "Slovenia", code: "+386"),
  PhoneCode(name: "Solomon Islands", code: "+677"),
  PhoneCode(name: "Somalia", code: "+252"),
  PhoneCode(name: "South Africa", code: "+27"),
  PhoneCode(name: "South Korea", code: "+82"),
  PhoneCode(name: "South Sudan", code: "+211"),
  PhoneCode(name: "Spain", code: "+34"),
  PhoneCode(name: "Sri Lanka", code: "+94"),
  PhoneCode(name: "Sudan", code: "+249"),
  PhoneCode(name: "Suriname", code: "+597"),
  PhoneCode(name: "Sweden", code: "+46"),
  PhoneCode(name: "Switzerland", code: "+41"),
  PhoneCode(name: "Syria", code: "+963"),
  PhoneCode(name: "Taiwan", code: "+886"),
  PhoneCode(name: "Tajikistan", code: "+992"),
  PhoneCode(name: "Tanzania", code: "+255"),
  PhoneCode(name: "Thailand", code: "+66"),
  PhoneCode(name: "Timor-Leste", code: "+670"),
  PhoneCode(name: "Togo", code: "+228"),
  PhoneCode(name: "Tonga", code: "+676"),
  PhoneCode(name: "Trinidad and Tobago", code: "+1-868"),
  PhoneCode(name: "Tunisia", code: "+216"),
  PhoneCode(name: "Turkey", code: "+90"),
  PhoneCode(name: "Turkmenistan", code: "+993"),
  PhoneCode(name: "Turks and Caicos Islands", code: "+1-649"),
  PhoneCode(name: "Tuvalu", code: "+688"),
  PhoneCode(name: "Uganda", code: "+256"),
  PhoneCode(name: "Ukraine", code: "+380"),
  PhoneCode(name: "United Arab Emirates", code: "+971"),
  PhoneCode(name: "United Kingdom", code: "+44"),
  PhoneCode(name: "United States", code: "+1"),
  PhoneCode(name: "Uruguay", code: "+598"),
  PhoneCode(name: "Uzbekistan", code: "+998"),
  PhoneCode(name: "Vanuatu", code: "+678"),
  PhoneCode(name: "Venezuela", code: "+58"),
  PhoneCode(name: "Vietnam", code: "+84"),
  PhoneCode(name: "Yemen", code: "+967"),
  PhoneCode(name: "Zambia", code: "+260"),
  PhoneCode(name: "Zimbabwe", code: "+263"),
];

const Map<String, List<String>> countryStates = {
  "United States": [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", 
    "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", 
    "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", 
    "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", 
    "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", 
    "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", 
    "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"
  ],
  "Canada": [
    "Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", 
    "Nova Scotia", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan", 
    "Northwest Territories", "Nunavut", "Yukon"
  ],
  "United Kingdom": [
    "England", "Scotland", "Wales", "Northern Ireland"
  ],
  "Nigeria": [
    "Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa", "Benue", "Borno", "Cross River", 
    "Delta", "Ebonyi", "Edo", "Ekiti", "Enugu", "FCT", "Gombe", "Imo", "Jigawa", "Kaduna", "Kano", 
    "Katsina", "Kebbi", "Kogi", "Kwara", "Lagos", "Nasarawa", "Niger", "Ogun", "Ondo", "Osun", "Oyo", 
    "Plateau", "Rivers", "Sokoto", "Taraba", "Yobe", "Zamfara"
  ],
  "India": [
    "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", 
    "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", 
    "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", 
    "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal"
  ],
  "Australia": [
    "New South Wales", "Queensland", "South Australia", "Tasmania", "Victoria", "Western Australia", 
    "Australian Capital Territory", "Northern Territory"
  ],
  "South Africa": [
    "Gauteng", "Western Cape", "KwaZulu-Natal", "Eastern Cape", "Free State", "Limpopo", 
    "Mpumalanga", "North West", "Northern Cape"
  ],
  "Ghana": [
    "Greater Accra", "Ashanti", "Eastern", "Western", "Northern", "Volta", "Central", 
    "Bono", "Bono East", "Ahafo", "Western North", "Oti", "Savannah", "North East", 
    "Upper East", "Upper West"
  ],
  "Kenya": [
    "Mombasa", "Kwale", "Kilifi", "Tana River", "Lamu", "Taita/Taveta", "Garissa", "Wajir", "Mandera", 
    "Marsabit", "Isiolo", "Meru", "Tharaka-Nithi", "Embu", "Kitui", "Machakos", "Makueni", "Nyandarua", 
    "Nyeri", "Kirinyaga", "Murang'a", "Kiambu", "Turkana", "West Pokot", "Samburu", "Trans Nzoia", 
    "Uasin Gishu", "Elgeyo/Marakwet", "Nandi", "Baringo", "Laikipia", "Nakuru", "Narok", "Kajiado", 
    "Kericho", "Bomet", "Kakamega", "Vihiga", "Bungoma", "Busia", "Siaya", "Kisumu", "Homa Bay", 
    "Migori", "Kisii", "Nyamira", "Nairobi"
  ]
};
